site_name: Quantum ESPRESSO for Solid State Physics
site_url: https://nguyen-group.github.io/lectures/QE-SSP/

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to dark mode
  features:
    - navigation.sections # Shows sections in navigation
    - navigation.indexes  # Shows section indexes in ToC
    - toc.integrate       # Integrates with content
    - toc.follow         # Highlights current section

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css

nav:
  - Overview: index.md
  - Course Details:
    - Contents: contents.md
    - Resources: resources.md
  - Lectures:
    - Introduction: lecture1.ipynb

plugins:
  - search
  - mkdocs-jupyter