site_name: Simple Docs
site_url: https://nguyen-group.github.io/lectures/QE-SSP/

theme:
  name: material
  palette:
    scheme: slate 
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.instant
    - toc.integrate
    - content.code.annotate
    - content.code.copy

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.arithmatex
  - attr_list  # Needed for citation styling

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - bibtex:
      bib_file: 'docs/refs.bib'  # Path to your .bib file
      csl_file: 'https://cdn.jsdelivr.net/gh/citation-style-language/styles@master/apa.csl'  # O